import React from'react';import{render,screen,fireEvent,waitFor,cleanup}from'@testing-library/react';import{beforeEach,afterEach,it,expect,vi}from'vitest';
const api=vi.hoisted(()=>({get:vi.fn(),post:vi.fn()}));vi.mock('../api.js',()=>({api}));vi.mock('../context.jsx',()=>({useApp:()=>({lang:'en'})}));import DemoSetup from'./DemoSetup.jsx';
const status={universities:[{id:1,name_en:'First'},{id:13,name_en:'Arak',code:'ARAK'}],cases:[{university_id:1,active:0}],accounts:[]};const result={universityId:1,accounts:[{username:'demo_student_1',role:'student',created:true,status:'active'}],caseIds:[101]};
beforeEach(()=>{vi.clearAllMocks();api.get.mockResolvedValue(status);api.post.mockResolvedValue(result)});afterEach(cleanup);
async function ready(){render(<DemoSetup/>);fireEvent.click(screen.getByText('Installation check & academic demo setup'));await screen.findByLabelText('Target university');fireEvent.change(screen.getByLabelText('Target university'),{target:{value:'1'}});fireEvent.change(screen.getByLabelText('New account password (at least 12 characters)'),{target:{value:'R30-local-password'}});fireEvent.click(screen.getByRole('checkbox'))}
it('locks destination, password and consent while the request is pending',async()=>{let resolve;api.post.mockImplementation(()=>new Promise(r=>resolve=r));await ready();fireEvent.click(screen.getByText('Prepare demo safely'));expect(screen.getByLabelText('Target university')).toBeDisabled();expect(screen.getByLabelText('New account password (at least 12 characters)')).toBeDisabled();expect(screen.getByRole('checkbox')).toBeDisabled();resolve(result)});
it('does not display a previous university success after changing the target',async()=>{await ready();fireEvent.click(screen.getByText('Prepare demo safely'));await screen.findByText('Prepared; account usernames:');fireEvent.change(screen.getByLabelText('Target university'),{target:{value:'13'}});expect(screen.queryByText('Prepared; account usernames:')).toBeNull();expect(screen.getByRole('checkbox')).not.toBeChecked()});
it('refreshes installation counts after a successful prepare',async()=>{await ready();fireEvent.click(screen.getByText('Prepare demo safely'));await screen.findByText('Prepared; account usernames:');await waitFor(()=>expect(api.get).toHaveBeenCalledTimes(2))});
it('clears the old request error when reopening successfully',async()=>{api.get.mockRejectedValueOnce(Error('Offline'));render(<DemoSetup/>);const toggle=screen.getByText('Installation check & academic demo setup');fireEvent.click(toggle);await screen.findByRole('alert');fireEvent.click(toggle);fireEvent.click(toggle);await screen.findByLabelText('Target university');expect(screen.queryByRole('alert')).toBeNull()});
it('shows the confirmed destination and retains success separately from a failed inventory refresh',async()=>{api.get.mockResolvedValueOnce(status).mockRejectedValueOnce(Error('Refresh offline'));await ready();fireEvent.click(screen.getByText('Prepare demo safely'));await screen.findByText('Prepared; account usernames:');expect(await screen.findByRole('alert')).toHaveTextContent('Installation status could not be refreshed');expect(screen.getByText('University #1')).toBeTruthy();expect(screen.getByText('Retry status')).not.toBeDisabled()});
it('prefers the emergency source university and distinguishes inventory from scientific approval',async()=>{api.get.mockResolvedValue({...status,emergency:[{university_id:13,active:7,inactive:1,retired:1,missing:0,invalid:1,modified:1}]});render(<DemoSetup/>);fireEvent.click(screen.getByText('Installation check & academic demo setup'));expect(await screen.findByLabelText('Target university')).toHaveValue('13');expect(screen.getByText(/This is software inventory/)).toHaveTextContent('Active 7/10');expect(screen.getByText(/This is software inventory/)).toHaveTextContent('Invalid 1')});
it('ignores a stale status request after closing and reopening',async()=>{let resolve;api.get.mockImplementationOnce(()=>new Promise(r=>resolve=r)).mockResolvedValueOnce({...status,universities:[{id:77,name_en:'Current'}]});render(<DemoSetup/>);const toggle=screen.getByText('Installation check & academic demo setup');fireEvent.click(toggle);fireEvent.click(toggle);fireEvent.click(toggle);expect(await screen.findByLabelText('Target university')).toHaveValue('77');resolve(status);await waitFor(()=>expect(screen.getByLabelText('Target university')).toHaveValue('77'));expect(screen.queryByRole('option',{name:'First (#1)'})).toBeNull()});
it('prevents double submission while preserving the password on failure for retry',async()=>{let reject;api.post.mockImplementation(()=>new Promise((_,r)=>reject=r));await ready();fireEvent.click(screen.getByText('Prepare demo safely'));fireEvent.click(screen.getByText('Preparing…'));expect(api.post).toHaveBeenCalledTimes(1);reject(Error('Disk unavailable'));expect(await screen.findByRole('alert')).toHaveTextContent('Disk unavailable');expect(screen.getByLabelText('New account password (at least 12 characters)')).toHaveValue('R30-local-password');expect(screen.getByText('Prepare demo safely')).not.toBeDisabled()});
