import SearchAnswer from './SearchAnswer.jsx';
import {stepOptions,stepCorrectIndex,stepBoolean} from '../lib/step-authoring.js';
export default function StepwiseEditor({steps,onChange,lang,catalogs=[]}){
 const fa=lang==='fa',text=(a,b)=>fa?a:b;
 const patch=(i,value)=>onChange(steps.map((s,j)=>j===i?{...s,...value}:s));
 const input=(s,i,key,label,multiline=false)=> <label className="field" data-content-language={key.endsWith('_fa')?'fa':'en'}>{label}{multiline?<textarea aria-label={label} dir={key.endsWith('_fa')?'rtl':'ltr'} value={s[key]||''} onChange={e=>patch(i,{[key]:e.target.value})}/>:<input aria-label={label} dir={key.endsWith('_fa')?'rtl':'ltr'} value={Array.isArray(s[key])?s[key].join(', '):(s[key]??'')} onChange={e=>patch(i,{[key]:e.target.value,...(key.startsWith('answer_')?{correct_index:null}:{})})}/>}</label>;
 return <section aria-label={text('مراحل سؤال','Question steps')}>
  <div className="section-title"><h3>{text('مراحل سؤال','Question steps')}</h3><button type="button" className="btn btn-sm" onClick={()=>onChange([...steps,{answerType:'autocomplete',prompt_fa:'',prompt_en:'',options_fa:[],options_en:[]}])}>{text('افزودن مرحله','Add step')}</button></div>
  {steps.map((s,i)=>{const type=s.answerType||s.type||'autocomplete',optsFA=stepOptions(s.options_fa),optsEN=stepOptions(s.options_en),count=Math.max(optsFA.length,optsEN.length),correct=stepCorrectIndex(s);
   const options=Array.from({length:count},(_,j)=>({fa:optsFA[j]||optsEN[j]||'',en:optsEN[j]||optsFA[j]||''}));
   const choose=j=>patch(i,{correct_index:j,answer_fa:options[j]?.fa||'',answer_en:options[j]?.en||'',accept_fa:[],accept_en:[]});
   return <fieldset key={i} className="card mb12" style={{padding:16,minWidth:0}}><legend>{text('مرحله','Step')} {i+1}</legend>
    <div className="section-title"><label className="field">{text('نوع پاسخ این مرحله','Step answer type')}<select aria-label={text('نوع پاسخ این مرحله','Step answer type')} value={type} onChange={e=>patch(i,{answerType:e.target.value})}><option value="autocomplete">{text('اتوکامپلیت','Autocomplete')}</option><option value="mcq">{text('چندگزینه‌ای','Multiple choice')}</option><option value="truefalse">{text('درست / غلط','True / False')}</option><option value="fill">{text('جای خالی','Fill in the blank')}</option></select></label>{steps.length>1&&<button className="btn btn-sm btn-danger" type="button" aria-label={text(`حذف مرحله ${i+1}`,`Remove step ${i+1}`)} onClick={()=>onChange(steps.filter((_,j)=>j!==i))}>{text('حذف مرحله','Remove step')}</button>}</div>
    <div className="grid grid-2">{input(s,i,'prompt_fa','Prompt FA',true)}{input(s,i,'prompt_en','Prompt EN',true)}</div>
    {type==='truefalse'?<label className="field">{text('پاسخ صحیح','Correct answer')}<select aria-label={text('پاسخ صحیح','Correct answer')} value={stepBoolean(s)===undefined?'':String(stepBoolean(s))} onChange={e=>patch(i,{answer:e.target.value==='true'})}><option value="" disabled>{text('انتخاب کنید','Choose')}</option><option value="true">{text('درست','True')}</option><option value="false">{text('غلط','False')}</option></select></label>:<>
     {(type==='autocomplete'||type==='mcq')&&<>
      <label className="field">{text('کاتالوگ پاسخ‌ها','Answer catalog')}<select aria-label={text('کاتالوگ پاسخ‌ها','Answer catalog')} value={s.catalogId||''} onChange={e=>{const c=catalogs.find(c=>String(c.id)===e.target.value);patch(i,c?{catalogId:e.target.value,options_fa:c.items.map(o=>o.fa||o.en||''),options_en:c.items.map(o=>o.en||o.fa||''),correct_index:null,answer_fa:'',answer_en:'',accept_fa:[],accept_en:[]}:{catalogId:''});}}><option value="">{text('ورود دستی','Manual options')}</option>{catalogs.map(c=><option key={c.id} value={c.id}>{(fa?c.name_fa:c.name_en)||c.name_fa||c.name_en}</option>)}</select></label>
      {type==='autocomplete'&&<><p className="small muted">{text('فهرست پیشنهادها برای دانشجو نمایش داده می‌شود؛ پاسخ صحیح را جداگانه مشخص کنید. بدون فهرست، پاسخ متنی آزاد است.','Students see the suggestion list, not the answer key. Without suggestions the answer is free text.')}</p><div className="grid grid-2">{['fa','en'].map(l=><label className="field" data-content-language={l} key={l}>{text('پیشنهادها؛ هر خط یک مورد','Suggestions; one per line')} {l.toUpperCase()}<textarea aria-label={`Suggestions ${l.toUpperCase()}`} value={stepOptions(s['options_'+l]).join('\n')} onChange={e=>patch(i,{['options_'+l]:e.target.value.split('\n')})}/></label>)}</div>{count>0&&<SearchAnswer options={options} lang={lang} onPick={choose} placeholder={text('انتخاب پاسخ صحیح از فهرست','Select the correct answer')}/>}</>}
      {type==='mcq'&&<><p className="small muted">{text('پاسخ صحیح را با دکمهٔ کنار گزینه تعیین کنید.','Mark one correct option.')}</p>{Array.from({length:Math.max(2,count)},(_,j)=><div key={j} className="card mb8" style={{padding:10}}><label><input type="radio" name={`step-correct-${i}`} aria-label={`Correct option ${j+1}`} checked={correct===j} onChange={()=>choose(j)}/>{text('پاسخ صحیح','Correct option')} {j+1}</label><div className="grid grid-2">{['fa','en'].map(l=><input key={l} data-content-language={l} aria-label={`Option ${j+1} ${l.toUpperCase()}`} placeholder={`Option ${j+1} ${l.toUpperCase()}`} value={stepOptions(s['options_'+l])[j]||''} onChange={e=>{const arr=Array.from({length:Math.max(2,count)},(_,k)=>stepOptions(s['options_'+l])[k]||'');arr[j]=e.target.value;patch(i,{['options_'+l]:arr});}}/>)}</div>{count>2&&<button type="button" className="btn btn-sm btn-danger" onClick={()=>patch(i,{options_fa:optsFA.filter((_,k)=>k!==j),options_en:optsEN.filter((_,k)=>k!==j),correct_index:correct===j?-1:correct>j?correct-1:correct,answer_fa:correct===j?'':s.answer_fa,answer_en:correct===j?'':s.answer_en,accept_fa:[],accept_en:[]})}>{text('حذف گزینه','Remove option')}</button>}</div>)}<button type="button" className="btn btn-sm" onClick={()=>patch(i,{options_fa:[...Array.from({length:Math.max(2,count)},(_,j)=>optsFA[j]||''),''],options_en:[...Array.from({length:Math.max(2,count)},(_,j)=>optsEN[j]||''),'']})}>{text('افزودن گزینه','Add option')}</button></>}
     </>}
     {type!=='mcq'&&<><p className="small muted">{type==='fill'?text('در متن مرحله از ___ برای محل جای خالی استفاده کنید.','Use ___ in the prompt to mark the blank.'):''}</p><div className="grid grid-2">{input(s,i,'answer_fa','Correct answer FA')}{input(s,i,'answer_en','Correct answer EN')}{input(s,i,'accept_fa','Accepted alternatives FA')}{input(s,i,'accept_en','Accepted alternatives EN')}</div></>}
    </>}
    <details className="mt12"><summary>{text('راهنما و توضیح مرحله','Step hints and explanation')}</summary><div className="grid grid-2">{input(s,i,'hint_fa','Hint FA')}{input(s,i,'hint_en','Hint EN')}{input(s,i,'explanation_fa','Explanation FA',true)}{input(s,i,'explanation_en','Explanation EN',true)}</div></details>
   </fieldset>;
  })}
 </section>;
}
