import {beforeAll,it,expect} from 'vitest';
import {execFileSync} from 'node:child_process';
import {initDb,db,persistNow,reloadDb} from '../src/db.js';
import {EMERGENCY_TEN} from '../src/data/vp-emergency-ten.js';
beforeAll(async()=>{execFileSync(process.execPath,['src/seed.js','--force'],{stdio:'ignore'});await initDb();},60000);
function uni(){return Number(db.prepare('INSERT INTO universities(name_fa,name_en,code) VALUES (?,?,?)').run('آزمون','R29',`R29-${Math.random()}`).lastInsertRowid)}
function add(u,data,active=1){return Number(db.prepare('INSERT INTO cases(data_json,difficulty,checklist_id,university_id,active) VALUES (?,\'hard\',1,?,?)').run(typeof data==='string'?data:JSON.stringify(data),u,active).lastInsertRowid)}
async function provision(u){persistNow({throwOnError:true});let error;try{execFileSync(process.execPath,['src/seed-emergency-ten.js'],{env:{...process.env,UNIVERSITY_ID:String(u)},stdio:'pipe'});}catch(e){error=e.stderr?.toString()||e.message}await reloadDb();return error;}
it('binds the active exact legacy patient, not its earlier archived copy',async()=>{const u=uni();const archived=add(u,EMERGENCY_TEN[0].data,0),active=add(u,EMERGENCY_TEN[0].data);expect(await provision(u)).toBeUndefined();expect(db.prepare('SELECT source_key FROM cases WHERE id=?').get(active).source_key).toBe(`medschool:emergency:1:university:${u}`);expect(db.prepare('SELECT source_key FROM cases WHERE id=?').get(archived).source_key).toBeNull();});
it('does not mistake a same-title different clinical chart for the supplied source',async()=>{const u=uni();const id=add(u,{...EMERGENCY_TEN[0].data,history_en:'Teacher-authored different chart'});expect(await provision(u)).toBeUndefined();expect(db.prepare('SELECT source_key FROM cases WHERE id=?').get(id).source_key).toBeNull();expect(JSON.parse(db.prepare('SELECT data_json FROM cases WHERE source_key=?').get(`medschool:emergency:1:university:${u}`).data_json)).toEqual(EMERGENCY_TEN[0].data);});
it('a malformed unrelated legacy row cannot prevent installing the ten patients',async()=>{const u=uni();const id=add(u,'{bad json');expect(await provision(u)).toBeUndefined();expect(db.prepare('SELECT COUNT(*) n FROM cases WHERE university_id=? AND source_key IS NOT NULL').get(u).n).toBe(10);expect(db.prepare('SELECT data_json FROM cases WHERE id=?').get(id).data_json).toBe('{bad json');});
it('repeat installation preserves IDs, public codes and the exact ten source payloads',async()=>{const u=uni();expect(await provision(u)).toBeUndefined();const rows=db.prepare('SELECT * FROM cases WHERE university_id=? ORDER BY id').all(u);expect(rows).toHaveLength(10);rows.forEach((row,i)=>{expect(JSON.parse(row.data_json)).toEqual(EMERGENCY_TEN[i].data);expect(row.checklist_id).toBe(EMERGENCY_TEN[i].checklist_id);expect(row.active).toBe(1)});expect(await provision(u)).toBeUndefined();expect(db.prepare('SELECT * FROM cases WHERE university_id=? ORDER BY id').all(u)).toEqual(rows);});
it('does not resurrect a deleted source or reactivate an inactive source',async()=>{const u=uni();await provision(u);const rows=db.prepare('SELECT id,public_code FROM cases WHERE university_id=? ORDER BY id').all(u);db.prepare('DELETE FROM cases WHERE id=?').run(rows[0].id);db.prepare('UPDATE cases SET active=0 WHERE id=?').run(rows[1].id);expect(await provision(u)).toBeUndefined();expect(db.prepare('SELECT COUNT(*) n FROM cases WHERE university_id=?').get(u).n).toBe(9);expect(db.prepare('SELECT active FROM cases WHERE id=?').get(rows[1].id).active).toBe(0);expect(db.prepare('SELECT deleted_at FROM content_identity_registry WHERE public_code=?').get(rows[0].public_code).deleted_at).toBeTruthy();});
it('keeps an edited provisioned chart and version unchanged',async()=>{const u=uni();await provision(u);const row=db.prepare('SELECT * FROM cases WHERE university_id=? ORDER BY id').get(u);const data=JSON.parse(row.data_json);data.history_en='Teacher revision';db.prepare('UPDATE cases SET data_json=?,version=7 WHERE id=?').run(JSON.stringify(data),row.id);expect(await provision(u)).toBeUndefined();expect(db.prepare('SELECT data_json,version,public_code FROM cases WHERE id=?').get(row.id)).toEqual({data_json:JSON.stringify(data),version:7,public_code:row.public_code});});
it('an inactive-only exact legacy case stays inactive and is not duplicated',async()=>{const u=uni();const id=add(u,EMERGENCY_TEN[0].data,0);expect(await provision(u)).toBeUndefined();expect(db.prepare('SELECT COUNT(*) n FROM cases WHERE university_id=?').get(u).n).toBe(10);expect(db.prepare('SELECT active,source_key FROM cases WHERE id=?').get(id)).toEqual({active:0,source_key:`medschool:emergency:1:university:${u}`});});
it('does not bind another university and competitive patient creation remains prohibited',async()=>{const other=uni(),u=uni(),foreign=add(other,EMERGENCY_TEN[0].data);expect(()=>add(u,{...EMERGENCY_TEN[0].data,track:'learn'})).toThrow('virtual_patient_university_only');await provision(u);for(const id of [foreign])expect(db.prepare('SELECT source_key FROM cases WHERE id=?').get(id).source_key).toBeNull();expect(db.prepare('SELECT COUNT(*) n FROM cases WHERE university_id=? AND source_key IS NOT NULL').get(u).n).toBe(10);});
it('missing required rubric rolls back all cases and source reservations',async()=>{const {ensureEmergencyCases}=await import('../src/lib/emergency-provision.js');const u=uni();const old=db.prepare('SELECT name_en FROM checklists WHERE id=3').get().name_en;db.prepare("UPDATE checklists SET name_en='Teacher custom rubric' WHERE id=3").run();try{expect(()=>ensureEmergencyCases({universityId:u})).toThrow('emergency_checklist_missing:3');expect(db.prepare('SELECT COUNT(*) n FROM cases WHERE university_id=?').get(u).n).toBe(0);expect(db.prepare('SELECT COUNT(*) n FROM content_identity_registry WHERE source_key LIKE ?').get(`%:university:${u}`).n).toBe(0);}finally{db.prepare('UPDATE checklists SET name_en=? WHERE id=3').run(old)}});
it('rejects an unknown target university without changing existing cases',async()=>{const {ensureEmergencyCases}=await import('../src/lib/emergency-provision.js');const n=db.prepare('SELECT COUNT(*) n FROM cases').get().n;expect(()=>ensureEmergencyCases({universityId:999999})).toThrow('invalid_university');expect(db.prepare('SELECT COUNT(*) n FROM cases').get().n).toBe(n)});

it('provisioning makes every supplied recorded study selectable without exposing its result',async()=>{
 const {ensureEmergencyCases}=await import('../src/lib/emergency-provision.js');const {DEFAULT_LAB_TESTS,DEFAULT_IMAGING,DEFAULT_PARACLINIC,cleanOrderList}=await import('../src/data/order-catalog-defaults.js');const {getSetting}=await import('../src/routes/content.js');const u=uni();ensureEmergencyCases({universityId:u});
 for(const [field,key,defaults]of [['labResults','order_catalog_lab',DEFAULT_LAB_TESTS],['imagingResults','order_catalog_imaging',DEFAULT_IMAGING],['paraclinicResults','order_catalog_paraclinic',DEFAULT_PARACLINIC]]){
  const catalog=cleanOrderList(getSetting(key,null),defaults);
  for(const c of EMERGENCY_TEN)for(const r of c.data[field]||[]){const item=catalog.find(x=>x.en===r.name_en);expect(item,`${field}: ${r.name_en}`).toBeTruthy();expect(Object.keys(item).sort()).toEqual(['aliases','en','fa']);}
 }
});
it('catalog migration preserves custom choices and does not re-add intentional later removals',async()=>{const {ensureEmergencyCases}=await import('../src/lib/emergency-provision.js');const u=uni();const up=db.prepare('INSERT INTO settings(key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value');db.prepare("DELETE FROM settings WHERE key='academic_emergency_catalog_v1'").run();const custom={fa:'ویژه',en:'Institution custom study',aliases:['custom-test']};up.run('order_catalog_lab',JSON.stringify([custom]));ensureEmergencyCases({universityId:u});const list=JSON.parse(db.prepare("SELECT value FROM settings WHERE key='order_catalog_lab'").get().value);expect(list[0]).toEqual(custom);expect(list.some(x=>x.en==='Sodium')).toBe(true);up.run('order_catalog_lab',JSON.stringify([custom]));ensureEmergencyCases({universityId:u});expect(JSON.parse(db.prepare("SELECT value FROM settings WHERE key='order_catalog_lab'").get().value)).toEqual([custom]);});
it('refuses catalog overflow atomically instead of saving invisible truncated required studies',async()=>{const {ensureEmergencyCases}=await import('../src/lib/emergency-provision.js');const u=uni();db.prepare("DELETE FROM settings WHERE key='academic_emergency_catalog_v1'").run();const original=JSON.stringify(Array.from({length:400},(_,i)=>({fa:'ویژه '+i,en:'Custom '+i,aliases:[]})));db.prepare("UPDATE settings SET value=? WHERE key='order_catalog_lab'").run(original);expect(()=>ensureEmergencyCases({universityId:u})).toThrow('emergency_catalog_capacity');expect(db.prepare('SELECT COUNT(*) n FROM cases WHERE university_id=?').get(u).n).toBe(0);expect(db.prepare("SELECT value FROM settings WHERE key='order_catalog_lab'").get().value).toBe(original);expect(db.prepare("SELECT 1 FROM settings WHERE key='academic_emergency_catalog_v1'").get()).toBeUndefined();});
