import {beforeAll,it,expect} from 'vitest';
import {execFileSync} from 'node:child_process';
import request from 'supertest';
import {initDb,db} from '../src/db.js';
import {createApp} from '../src/app.js';
import {signToken} from '../src/lib/auth.js';
import {parseCSV,toCSV} from '../src/lib/csv.js';
import {itemAnalysisCsv} from '../src/lib/itemanalysis.js';
let app,uni,seq=0;
const run=(s,...a)=>Number(db.prepare(s).run(...a).lastInsertRowid);
function user(role='student'){const name='r28-'+(++seq),id=run("INSERT INTO users(username,student_no,password_hash,role,status,university_id,name_en) VALUES (?,?,'fixture',?,'active',?,'R28')",name,name,role,uni);return {id,token:signToken(db.prepare('SELECT * FROM users WHERE id=?').get(id))};}
const get=(url,u)=>request(app).get('/api'+url).set('Authorization',`Bearer ${u.token}`);
function form(key='answer',value='ordinary',anonymous=false){const teacher=user('teacher'),student=user();const id=run("INSERT INTO questionnaire_forms(title_en,scope,created_by,anonymous,questions_json) VALUES ('R28','general',?,?,?)",teacher.id,Number(anonymous),JSON.stringify([{id:key,type:'text'}]));run("INSERT INTO questionnaire_responses(form_id,user_id,pseudonym,context_type,answers_json) VALUES (?,?,?,'general',?)",id,anonymous?null:student.id,'r28-pseudo-'+seq,JSON.stringify({[key]:value}));return {teacher,student,id};}
function classroom(){const teacher=user('teacher'),student=user();const id=run("INSERT INTO classes(name_en,code,owner_id,university_id,log_transcript) VALUES ('R28',?,?,?,1)",'r28-'+seq,teacher.id,uni);run('INSERT INTO class_members(class_id,user_id) VALUES (?,?)',id,student.id);return {teacher,student,id};}
beforeAll(async()=>{execFileSync(process.execPath,['src/seed.js','--force'],{stdio:'ignore'});await initDb();uni=run("INSERT INTO universities(name_en,code) VALUES ('R28','r28')");app=createApp();},60000);
for(const text of ['=1+1','+1+1','-1+1','@SUM(1,2)','\t=1+1','\r=1+1','\n=1+1','＝1+1','＋1+1','－1+1','＠SUM(1,2)','  =1+1'])it(`questionnaire text is neutralized only on export: ${JSON.stringify(text)}`,async()=>{
 const f=form('answer',text);const before=db.prepare('SELECT answers_json FROM questionnaire_responses WHERE form_id=?').get(f.id);const r=await get(`/questionnaires/admin/forms/${f.id}/responses.csv`,f.teacher);expect(r.status).toBe(200);expect(parseCSV(r.text)[0].answer).toBe("'"+text);expect(db.prepare('SELECT answers_json FROM questionnaire_responses WHERE form_id=?').get(f.id)).toEqual(before);
});
for(const key of ['item,one','item"one','item\r\none','=1+1'])it(`questionnaire dynamic header is one safe field: ${JSON.stringify(key)}`,async()=>{
 const f=form(key,'preserved');const r=await get(`/questionnaires/admin/forms/${f.id}/responses.csv`,f.teacher);expect(r.status).toBe(200);const row=parseCSV(r.text)[0];expect(row[key.startsWith('=')?"'"+key:key]).toBe('preserved');expect(Object.keys(row)).toHaveLength(6);
});
it('questionnaire timestamp is escaped once',async()=>{const f=form();const value='legacy, "timestamp"';db.prepare('UPDATE questionnaire_responses SET updated_at=? WHERE form_id=?').run(value,f.id);const r=await get(`/questionnaires/admin/forms/${f.id}/responses.csv`,f.teacher);expect(parseCSV(r.text)[0].submitted_at).toBe(value);});
for(const name of ['=1+1','first\rsecond'])it(`gradebook preserves one safe name field: ${JSON.stringify(name)}`,async()=>{const f=classroom();db.prepare('UPDATE users SET name_en=? WHERE id=?').run(name,f.student.id);const r=await get(`/classes/${f.id}/gradebook.csv?lang=en`,f.teacher);expect(r.status).toBe(200);expect(parseCSV(r.text)[0].name).toBe(name.startsWith('=')?"'"+name:name);});
it('conversation export escapes student number and neutralizes event text',async()=>{
 const f=classroom(),studentNo='=1+1, "number"';db.prepare('UPDATE users SET student_no=? WHERE id=?').run(studentNo,f.student.id);const sid=run('INSERT INTO vp_sessions(user_id,case_id,class_id,logging_enabled) VALUES (?,1,?,1)',f.student.id,f.id);run("INSERT INTO vp_session_events(session_id,seq,at_ms,kind,payload_json) VALUES (?,1,0,'message',?)",sid,JSON.stringify({text:'=1+1'}));const r=await get(`/classes/${f.id}/conversation-log.csv`,f.teacher);expect(r.status).toBe(200);const row=parseCSV(r.text)[0];expect(row.student_no).toBe("'"+studentNo);expect(row.text).toBe("'=1+1");expect(Object.keys(row)).toHaveLength(11);
});
it('result export treats formula-prefixed student name as text',async()=>{const t=user('teacher'),s=user();db.prepare("UPDATE users SET name_en='=1+1' WHERE id=?").run(s.id);const id=run("INSERT INTO attempts(user_id,type,score) VALUES (?,'vp',-3)",s.id);const r=await get('/reports/export.csv',t);expect(r.status).toBe(200);const row=parseCSV(r.text).find(x=>Number(x.id)===id);expect(row.student).toBe("'=1+1");expect(row.score).toBe('-3');});
for(const text of ['=1+1','first\rsecond'])it(`item analysis exports one safe item label: ${JSON.stringify(text)}`,()=>{const csv=itemAnalysisCsv([{label_en:text,topic:'=1+1',n:2,facility:50,discrimination:-0.5,avgHints:0}],false),row=parseCSV(csv)[0];expect(row.Item).toBe(text.startsWith('=')?"'"+text:text);expect(row.Topic).toBe("'=1+1");expect(row['Discrimination D']).toBe('-0.5');});
it('default interchange CSV preserves formula-like text for round-trip consumers',()=>{const csv=toCSV([{answer:'=1+1'}],['answer']);expect(parseCSV(csv)[0].answer).toBe('=1+1');});
it('spreadsheet export keeps real negative numbers numeric',()=>{const csv=toCSV([{score:-3.5,text:'-3.5'}],['score','text'],{spreadsheetSafe:true});const row=parseCSV(csv)[0];expect(row.score).toBe('-3.5');expect(row.text).toBe("'-3.5");});
it('ordinary Persian multiline response and booleans preserve their values',async()=>{const text='پاسخ، "دقیق"\nخط دوم',f=form('answer',text);let r=await get(`/questionnaires/admin/forms/${f.id}/responses.csv`,f.teacher);expect(parseCSV(r.text)[0].answer).toBe(text);db.prepare('UPDATE questionnaire_responses SET answers_json=? WHERE form_id=?').run(JSON.stringify({answer:false}),f.id);r=await get(`/questionnaires/admin/forms/${f.id}/responses.csv`,f.teacher);expect(parseCSV(r.text)[0].answer).toBe('0');});
it('anonymous questionnaire export stays de-identified while protecting text',async()=>{const f=form('answer','=1+1',true);const r=await get(`/questionnaires/admin/forms/${f.id}/responses.csv`,f.teacher);const row=parseCSV(r.text)[0];expect(row.answer).toBe("'=1+1");expect(row).not.toHaveProperty('student_no');expect(row).not.toHaveProperty('participant');expect(db.prepare('SELECT user_id FROM questionnaire_responses WHERE form_id=?').get(f.id).user_id).toBeNull();});
it('foreign teacher cannot export a questionnaire or class gradebook',async()=>{const f=form(),cl=classroom(),foreign=user('teacher');db.prepare('UPDATE users SET university_id=1 WHERE id=?').run(foreign.id);for(const url of [`/questionnaires/admin/forms/${f.id}/responses.csv`,`/classes/${cl.id}/gradebook.csv`,`/classes/${cl.id}/conversation-log.csv`])expect((await get(url,foreign)).status).toBe(403);});
it('students cannot call staff report exporters',async()=>{const f=form(),cl=classroom();for(const url of [`/questionnaires/admin/forms/${f.id}/responses.csv`,`/classes/${cl.id}/gradebook.csv`,`/classes/${cl.id}/conversation-log.csv`,'/reports/export.csv'])expect((await get(url,f.student)).status).toBe(403);});
it('generic CSV quotes dynamic headers without changing record lookup keys',()=>{const key='label, "one"\r\ntwo',csv=toCSV([{[key]:'normal'}],[key]);expect(parseCSV(csv)[0][key]).toBe('normal');});
