import {beforeAll,afterEach,it,expect,vi} from 'vitest';import {execFileSync} from 'node:child_process';import fs from 'node:fs';import request from 'supertest';
import {db,initDb,persistNow,reloadDb} from '../src/db.js';import {DB_PATH} from '../src/lib/paths.js';import {createApp} from '../src/app.js';import {signToken} from '../src/lib/auth.js';import * as passwords from '../src/lib/password.js';
let app,n=0;const stamp=Date.now().toString(36),run=(s,...a)=>Number(db.prepare(s).run(...a).lastInsertRowid),rows=(s,...a)=>db.prepare(s).all(...a);
function actor(role,uni=null){const username=`r25-${stamp}-${++n}`,id=run("INSERT INTO users(username,student_no,password_hash,role,status,university_id) VALUES (?,?,'fixture',?,'active',?)",username,username,role,uni);return {id,username,token:signToken(db.prepare('SELECT * FROM users WHERE id=?').get(id))};}
function fixture(){const uni=run("INSERT INTO universities(name_en,code) VALUES ('R25',?)",`R25-${stamp}-${++n}`),admin=actor('admin'),teacher=actor('teacher',uni),student=actor('student',uni);const catalog=run("INSERT INTO catalogs(name_en,items_json,owner_id) VALUES ('R25 original','[]',?)",teacher.id),checklist=run("INSERT INTO checklists(name_en,items_json,owner_id) VALUES ('R25 original','[]',?)",teacher.id),cid=run("INSERT INTO cases(data_json,university_id,checklist_id) VALUES ('{}',?,1)",uni);return {uni,admin,teacher,student,catalog,checklist,cid};}
const call=(method,path,u,body={})=>request(app)[method]('/api'+path).set('Authorization',`Bearer ${u.token}`).send(body);
beforeAll(async()=>{execFileSync(process.execPath,['src/seed.js','--force'],{stdio:'ignore'});await initDb();app=createApp();},60000);afterEach(()=>vi.restoreAllMocks());
const writes=[
 ['catalog create',f=>['post','/catalogs',f.teacher,{name_en:`R25 new ${f.catalog}`,items:['one']}],f=>rows('SELECT * FROM catalogs WHERE name_en=?',`R25 new ${f.catalog}`)],
 ['catalog update',f=>['put',`/catalogs/${f.catalog}`,f.teacher,{name_en:'R25 changed',items:['two']}],f=>rows('SELECT * FROM catalogs WHERE id=?',f.catalog)],
 ['catalog delete',f=>['delete',`/catalogs/${f.catalog}`,f.teacher],f=>rows('SELECT * FROM catalogs WHERE id=?',f.catalog)],
 ['checklist create',f=>['post','/checklists',f.teacher,{name_en:`R25 new ${f.checklist}`,items:[]}],f=>rows('SELECT * FROM checklists WHERE name_en=?',`R25 new ${f.checklist}`)],
 ['checklist update',f=>['put',`/checklists/${f.checklist}`,f.teacher,{name_en:'R25 changed',items:[{id:'one',weight:1}]}],f=>rows('SELECT * FROM checklists WHERE id=?',f.checklist)],
 ['checklist delete',f=>['delete',`/checklists/${f.checklist}`,f.teacher],f=>rows('SELECT * FROM checklists WHERE id=?',f.checklist)],
 ['assignment replace',f=>['put',`/assignments/${f.student.id}`,f.teacher,{caseIds:[f.cid],maxAttempts:2}],f=>rows('SELECT * FROM exam_assignments WHERE user_id=?',f.student.id)],
 ['password reset',f=>['put',`/users/${f.student.id}/password`,f.teacher,{password:'R25-local-new'}],f=>rows('SELECT password_hash,token_ver FROM users WHERE id=?',f.student.id)],
 ['account status',f=>['put',`/users/${f.student.id}/status`,f.teacher,{status:'inactive'}],f=>rows('SELECT status,token_ver FROM users WHERE id=?',f.student.id)],
];
for(const[name,spec,read]of writes)it(`${name}: failed save rolls back and successful retry survives reload`,async()=>{const f=fixture(),before=read(f);persistNow({throwOnError:true});const rename=fs.renameSync;let hit=false;vi.spyOn(fs,'renameSync').mockImplementation((src,dst)=>{if(dst===DB_PATH&&JSON.stringify(read(f))!==JSON.stringify(before)){hit=true;throw Error('R25 save failure');}return rename(src,dst);});const r=await call(...spec(f));vi.restoreAllMocks();expect(r.status).toBe(503);expect(hit).toBe(true);expect(read(f)).toEqual(before);await reloadDb();expect(read(f)).toEqual(before);expect((await call(...spec(f))).status).toBe(200);const saved=read(f);expect(saved).not.toEqual(before);await reloadDb();expect(read(f)).toEqual(saved);});
it('password reset invalidates the target old token',async()=>{const f=fixture();expect((await call('get','/auth/me',f.student)).status).toBe(200);expect((await call('put',`/users/${f.student.id}/password`,f.teacher,{password:'R25-local-new'})).status).toBe(200);expect((await call('get','/auth/me',f.student)).status).toBe(401);});
it('deactivation then reactivation cannot resurrect an old session',async()=>{const f=fixture();expect((await call('put',`/users/${f.student.id}/status`,f.teacher,{status:'inactive'})).status).toBe(200);expect((await call('put',`/users/${f.student.id}/status`,f.teacher,{status:'active'})).status).toBe(200);expect((await call('get','/auth/me',f.student)).status).toBe(401);});
for(const method of ['password','status','assignment read','assignment write'])it(`university one teacher cannot manage an unassigned student: ${method}`,async()=>{const f=fixture(),t=actor('teacher',1);db.prepare('UPDATE users SET university_id=NULL WHERE id=?').run(f.student.id);const before=rows('SELECT * FROM users WHERE id=?',f.student.id);let r;if(method==='password')r=await call('put',`/users/${f.student.id}/password`,t,{password:'not-allowed'});else if(method==='status')r=await call('put',`/users/${f.student.id}/status`,t,{status:'inactive'});else r=await call(method.endsWith('read')?'get':'put',`/assignments/${f.student.id}`,t,{caseIds:[]});expect(r.status).toBe(403);expect(rows('SELECT * FROM users WHERE id=?',f.student.id)).toEqual(before);});
it('teacher without a university cannot list unrelated unassigned students',async()=>{const t=actor('teacher'),u=actor('student');const r=await call('get','/users',t);expect(r.status).toBe(400);expect(JSON.stringify(r.body)).not.toContain(u.username);});
for(const change of ['target transferred','actor transferred','actor demoted','actor revoked'])it(`password reset rechecks access after hashing: ${change}`,async()=>{const f=fixture();let entered,release;const gate=new Promise(r=>entered=r);vi.spyOn(passwords,'hashPassword').mockImplementation(()=>{entered();return new Promise(r=>release=r);});const response=call('put',`/users/${f.student.id}/password`,f.teacher,{password:'not-allowed'}).then(r=>r);await gate;
 if(change==='target transferred')db.prepare('UPDATE users SET university_id=1 WHERE id=?').run(f.student.id);else if(change==='actor transferred')db.prepare('UPDATE users SET university_id=1 WHERE id=?').run(f.teacher.id);else if(change==='actor demoted')db.prepare("UPDATE users SET role='student' WHERE id=?").run(f.teacher.id);else db.prepare('UPDATE users SET token_ver=token_ver+1 WHERE id=?').run(f.teacher.id);
 release('R25 synthetic changed hash');expect((await response).status).toBe(403);expect(rows('SELECT password_hash FROM users WHERE id=?',f.student.id)[0].password_hash).toBe('fixture');});
it('password reset rechecks a per-device logout after hashing',async()=>{const f=fixture();let entered,release;const gate=new Promise(r=>entered=r);vi.spyOn(passwords,'hashPassword').mockImplementation(()=>{entered();return new Promise(r=>release=r);});const response=call('put',`/users/${f.student.id}/password`,f.teacher,{password:'not-allowed'}).then(r=>r);await gate;expect((await call('post','/auth/logout',f.teacher)).status).toBe(200);release('R25 synthetic changed hash');expect((await response).status).toBe(403);expect(rows('SELECT password_hash FROM users WHERE id=?',f.student.id)[0].password_hash).toBe('fixture');});
it('admin can reset an unassigned student and the new password can log in',async()=>{const f=fixture();db.prepare('UPDATE users SET university_id=NULL WHERE id=?').run(f.student.id);expect((await call('put',`/users/${f.student.id}/password`,f.admin,{password:'R25-new-login'})).status).toBe(200);const login=await request(app).post('/api/auth/login').send({username:f.student.username,password:'R25-new-login'});expect(login.status).toBe(200);});
it('setting an already active account active keeps its session',async()=>{const f=fixture();expect((await call('put',`/users/${f.student.id}/status`,f.teacher,{status:'active'})).status).toBe(200);expect((await call('get','/auth/me',f.student)).status).toBe(200);});
it('hashing errors are forwarded and do not change the password',async()=>{const f=fixture();vi.spyOn(passwords,'hashPassword').mockRejectedValue(Error('R25 hash failure'));expect((await call('put',`/users/${f.student.id}/password`,f.teacher,{password:'R25-new-login'})).status).toBe(500);expect(rows('SELECT password_hash FROM users WHERE id=?',f.student.id)[0].password_hash).toBe('fixture');});
