import{beforeAll,it,expect}from'vitest';import{execFileSync}from'node:child_process';import request from'supertest';import{initDb,db,persistNow,reloadDb}from'../src/db.js';import{createApp}from'../src/app.js';import{signToken}from'../src/lib/auth.js';let app,admin,student,id,n=0;const saved=()=>db.prepare('SELECT * FROM exam_assignments WHERE user_id=? ORDER BY case_id').all(id);const put=body=>request(app).put('/api/assignments/'+id).auth(admin,{type:'bearer'}).send(body);
beforeAll(async()=>{execFileSync(process.execPath,['src/seed.js','--force'],{stdio:'ignore'});await initDb();app=createApp();admin=signToken(db.prepare("SELECT * FROM users WHERE username='admin'").get());id=Number(db.prepare("INSERT INTO users(username,password_hash,role,status,university_id) VALUES ('r31-target','fixture','student','active',1)").run().lastInsertRowid);student=signToken(db.prepare('SELECT * FROM users WHERE id=?').get(id));db.prepare('INSERT INTO exam_assignments(user_id,case_id,assigned_by,max_attempts) VALUES (?,1,1,5)').run(id)},60000);
for(const body of [{},{caseIds:null},{caseIds:'1'},{caseIds:{}},{caseIds:[1,'bad']},{caseIds:[1,0]},{caseIds:Array(401).fill(1)}])it(`rejects malformed replacement ${JSON.stringify(body).slice(0,60)} without disabling access`,async()=>{const before=saved();const r=await put(body);expect(r.status).toBe(400);expect(saved()).toEqual(before)});
for(const maxAttempts of [0,-1,1.5,'not-a-number',null,true,'',9007199254740992])it(`rejects invalid attempt limit ${JSON.stringify(maxAttempts)} without writes`,async()=>{const before=saved();expect((await put({caseIds:[1],maxAttempts})).status).toBe(400);expect(saved()).toEqual(before)});
for(const maxAttempts of [-1,'not-a-number',null])it(`rejects invalid initial assignment limit ${JSON.stringify(maxAttempts)} before creating the student`,async()=>{const username='r31-new-'+(++n);const r=await request(app).post('/api/users').auth(admin,{type:'bearer'}).send({username,password:'R31-local-only',role:'student',university_id:1,caseIds:[1],maxAttempts});expect(r.status).toBe(400);expect(db.prepare('SELECT id FROM users WHERE username=?').get(username)).toBeUndefined()});
it('explicit empty list still revokes all grants',async()=>{expect((await put({caseIds:[]})).status).toBe(200);expect(saved().every(r=>r.active===0)).toBe(true)});
it('numeric strings normalize, duplicate IDs deduplicate, and positive integer quota is retained',async()=>{const r=await put({caseIds:['1',1],maxAttempts:' 7 '});expect(r.status).toBe(200);expect(r.body).toMatchObject({added:1,skipped:1});expect(saved().find(r=>r.case_id===1)).toMatchObject({active:1,max_attempts:7})});
it('omitted quota defaults to one on a valid replacement',async()=>{expect((await put({caseIds:[1]})).status).toBe(200);expect(saved().find(r=>r.case_id===1).max_attempts).toBe(1)});
it('valid integer foreign-university case IDs remain filtered rather than granted',async()=>{const foreign=Number(db.prepare("INSERT INTO cases(data_json,difficulty,checklist_id,university_id) VALUES ('{\"title_en\":\"Other\"}','easy',1,2)").run().lastInsertRowid);const r=await put({caseIds:[1,foreign],maxAttempts:2});expect(r.status).toBe(200);expect(r.body).toMatchObject({added:1,skipped:1});expect(saved().some(r=>r.case_id===foreign)).toBe(false)});
it('students cannot replace their own grants, even with valid input',async()=>{const before=saved();expect((await request(app).put('/api/assignments/'+id).auth(student,{type:'bearer'}).send({caseIds:[],maxAttempts:100})).status).toBe(403);expect(saved()).toEqual(before)});
it('teacher from another university remains forbidden before mutation',async()=>{const tid=Number(db.prepare("INSERT INTO users(username,password_hash,role,status,university_id) VALUES ('r31-foreign-teacher','fixture','teacher','active',2)").run().lastInsertRowid);const token=signToken(db.prepare('SELECT * FROM users WHERE id=?').get(tid));const before=saved();expect((await request(app).put('/api/assignments/'+id).auth(token,{type:'bearer'}).send({caseIds:[]})).status).toBe(403);expect(saved()).toEqual(before)});
it('student creation without assignments keeps its existing contract',async()=>{const username='r31-optional-'+(++n);const r=await request(app).post('/api/users').auth(admin,{type:'bearer'}).send({username,role:'student',university_id:1});expect(r.status).toBe(200);expect(db.prepare('SELECT COUNT(*) n FROM exam_assignments WHERE user_id=?').get(r.body.id).n).toBe(0)});
it('malformed initial IDs reject before creating an account',async()=>{const username='r31-bad-list-'+(++n);expect((await request(app).post('/api/users').auth(admin,{type:'bearer'}).send({username,role:'student',university_id:1,caseIds:'1'})).status).toBe(400);expect(db.prepare('SELECT id FROM users WHERE username=?').get(username)).toBeUndefined()});
it('valid initial assignment quota persists on the new student',async()=>{const username='r31-valid-'+(++n);const r=await request(app).post('/api/users').auth(admin,{type:'bearer'}).send({username,role:'student',university_id:1,caseIds:['1'],maxAttempts:'4'});expect(r.status).toBe(200);expect(db.prepare('SELECT max_attempts FROM exam_assignments WHERE user_id=?').get(r.body.id).max_attempts).toBe(4)});
it('rejects 401 distinct cases instead of silently applying only the first 400',async()=>{const ids=[];try{for(let i=0;i<401;i++)ids.push(Number(db.prepare("INSERT INTO cases(data_json,difficulty,checklist_id,university_id) VALUES ('{}','easy',1,1)").run().lastInsertRowid));const before=saved();const r=await put({caseIds:ids,maxAttempts:2});expect(r.status).toBe(400);expect(saved()).toEqual(before)}finally{db.prepare('DELETE FROM exam_assignments WHERE user_id=? AND case_id>23').run(id);for(const cid of ids)db.prepare('DELETE FROM cases WHERE id=?').run(cid)}});

it('rejection and a valid retry preserve their respective states after DB reload',async()=>{persistNow({throwOnError:true});const before=saved();expect((await put({maxAttempts:2})).status).toBe(400);await reloadDb();expect(saved()).toEqual(before);expect((await put({caseIds:[1],maxAttempts:6})).status).toBe(200);await reloadDb();expect(saved().find(r=>r.case_id===1)).toMatchObject({active:1,max_attempts:6})});
