import {beforeAll,afterEach,it,expect,vi} from 'vitest';import {execFileSync} from 'node:child_process';import fs from 'node:fs';import request from 'supertest';
import {initDb,db,persistNow,reloadDb} from '../src/db.js';import {DB_PATH} from '../src/lib/paths.js';import {createApp} from '../src/app.js';import {signToken} from '../src/lib/auth.js';
const stamp=Date.now().toString(36).toUpperCase();let app,n=0;const run=(s,...a)=>Number(db.prepare(s).run(...a).lastInsertRowid);const rows=(s,...a)=>db.prepare(s).all(...a);
function actor(role,uni=null){const username='r23-'+stamp+'-'+(++n);const id=run("INSERT INTO users(username,student_no,password_hash,role,university_id,status) VALUES (?,?,'fixture',?,?,'active')",username,username,role,uni);return {id,username,token:signToken(db.prepare('SELECT * FROM users WHERE id=?').get(id))};}
function fixture(){const code='R23-'+stamp+'-'+(++n),uni=run("INSERT INTO universities(name_en,code) VALUES ('R23 original',?)",code),other=run("INSERT INTO universities(name_en,code) VALUES ('R23 other',?)",code+'-other'),admin=actor('admin'),teacher=actor('teacher',uni),student=actor('student',uni),unassigned=actor('student');const cid=run("INSERT INTO classes(name_en,code,university_id) VALUES ('R23',?,?)",code,uni),eid=run("INSERT INTO exams(title_en,university_id) VALUES ('R23',?)",uni);return {uni,other,code,admin,teacher,student,unassigned,cid,eid};}
const call=(m,p,u,b={})=>request(app)[m]('/api'+p).set('Authorization',`Bearer ${u.token}`).send(b);
const count=f=>rows("SELECT COUNT(*) n FROM users WHERE role='student' AND university_id=?",f.uni)[0].n;
const limit=(f,extra=0)=>db.prepare('UPDATE universities SET limits_enabled=1,max_students=? WHERE id=?').run(count(f)+extra,f.uni);
const csv=f=>`name,student_no\nTest,${f.unassigned.username}`;
beforeAll(async()=>{execFileSync(process.execPath,['src/seed.js','--force'],{stdio:'ignore'});await initDb();app=createApp();},60000);afterEach(()=>vi.restoreAllMocks());
const quotas=[
 ['class members',f=>['put',`/classes/${f.cid}/members`,f.teacher,{userIds:[f.unassigned.id]}]],
 ['class resolve',f=>['post',`/classes/${f.cid}/members/resolve`,f.teacher,{studentNos:[f.unassigned.username]}]],
 ['exam ids',f=>['put',`/exams/${f.eid}/participants`,f.teacher,{userIds:[f.unassigned.id]}]],
 ['exam numbers',f=>['put',`/exams/${f.eid}/participants`,f.teacher,{studentNos:[f.unassigned.username]}]],
 ['exam resolve',f=>['post',`/exams/${f.eid}/participants/resolve`,f.teacher,{studentNos:[f.unassigned.username]}]],
 ['CSV existing user',f=>['post','/users/import',f.teacher,{csv:csv(f),university_id:f.uni,class_id:f.cid}]],
 ['CSV class-only destination',f=>['post','/users/import',f.admin,{csv:`name,student_no\nTest,new-${f.cid}`,class_id:f.cid}]],
 ['CSV row class-code destination',f=>['post','/users/import',f.admin,{csv:`name,student_no,class_code\nTest,new-${f.cid},${f.code}`}]],
 ['create student',f=>['post','/users',f.teacher,{studentNo:`new-${f.cid}`,name_en:'New student'}]],
];
for(const [name,spec] of quotas)it(`${name} cannot grow a full university`,async()=>{const f=fixture();limit(f);const before=count(f);await call(...spec(f));expect(count(f)).toBe(before);expect(rows('SELECT university_id FROM users WHERE id=?',f.unassigned.id)[0].university_id).toBeNull();});
const writes=[
 ['university create',f=>['post','/universities',f.admin,{name_en:'R23 added',code:f.code+'-new',limits_enabled:true,max_students:2}],f=>rows('SELECT * FROM universities WHERE code=?',f.code+'-new')],
 ['university edit',f=>['put',`/universities/${f.uni}`,f.admin,{name_en:'R23 updated',max_students:50}],f=>rows('SELECT * FROM universities WHERE id=?',f.uni)],
 ['university defaults',f=>['put','/universities/defaults',f.admin,{flash_no_penalty:true,live_board_speed:true}],f=>rows("SELECT * FROM settings WHERE key IN ('default_flash_no_penalty','default_live_board_speed') ORDER BY key")],
 ['university member add',f=>['post',`/universities/${f.uni}/members`,f.admin,{userIds:[f.unassigned.id]}],f=>rows('SELECT * FROM users WHERE id=?',f.unassigned.id)],
 ['university member remove',f=>['delete',`/universities/${f.uni}/members/${f.student.id}`,f.admin],f=>rows('SELECT * FROM users WHERE id=?',f.student.id)],
 ['university delete',f=>['delete',`/universities/${f.other}`,f.admin],f=>rows('SELECT * FROM universities WHERE id=?',f.other)],
 ['student create',f=>['post','/users',f.teacher,{studentNo:`new-${f.cid}`,name_en:'R23 new'}],f=>rows('SELECT * FROM users WHERE username=?',`new-${f.cid}`)],
 ['CSV create and enrol',f=>['post','/users/import',f.teacher,{csv:`name,student_no\nTest,new-${f.cid}`,class_id:f.cid}],f=>({users:rows('SELECT * FROM users WHERE username=?',`new-${f.cid}`),members:rows('SELECT * FROM class_members WHERE class_id=?',f.cid)})],
];
for(const [name,spec,read] of writes)it(`${name}: failure rolls back, retry and reload preserve the successful write`,async()=>{
 const f=fixture();if(name==='university defaults'){db.prepare("INSERT OR REPLACE INTO settings(key,value) VALUES ('default_flash_no_penalty','0'),('default_live_board_speed','0')").run();}const before=read(f);persistNow({throwOnError:true});const rename=fs.renameSync;let injected=false;
 vi.spyOn(fs,'renameSync').mockImplementation((src,dst)=>{if(dst===DB_PATH&&JSON.stringify(read(f))!==JSON.stringify(before)){injected=true;throw Error('R23 disk failure');}return rename(src,dst);});
 const specArgs=spec(f),r=await call(...specArgs);vi.restoreAllMocks();expect(r.status).toBe(name.startsWith("student") || name.startsWith("CSV") ? 503 : 500);expect(injected).toBe(true);expect(read(f)).toEqual(before);await reloadDb();expect(read(f)).toEqual(before);expect((await call(...specArgs)).status).toBe(200);const saved=read(f);expect(saved).not.toEqual(before);await reloadDb();expect(read(f)).toEqual(saved);
});
it('CSV teacher without a university cannot select one in the request',async()=>{const f=fixture();db.prepare('UPDATE users SET university_id=NULL WHERE id=?').run(f.teacher.id);expect((await call('post','/users/import',f.teacher,{csv:`name,student_no\nTest,new-${f.cid}`,university_id:f.other})).status).toBe(400);expect(rows('SELECT * FROM users WHERE username=?',`new-${f.cid}`)).toHaveLength(0);});
it('CSV student import cannot alter or enrol an administrator account',async()=>{const f=fixture(),before=rows('SELECT * FROM users WHERE id=?',f.admin.id);const r=await call('post','/users/import',f.teacher,{csv:`name,student_no\nTest,${f.admin.username}`,class_id:f.cid});expect(r.status).toBe(200);expect(rows('SELECT * FROM users WHERE id=?',f.admin.id)).toEqual(before);expect(rows('SELECT * FROM class_members WHERE user_id=?',f.admin.id)).toHaveLength(0);});
it('CSV duplicate row is counted once rather than twice',async()=>{const f=fixture();const r=await call('post','/users/import',f.teacher,{csv:`name,student_no\nTest,new-${f.cid}\nAgain,new-${f.cid}`});expect(r.status).toBe(200);expect(r.body).toMatchObject({created:1,skipped:1,total:2});});
it('editing university licensing preserves omitted inactive state',async()=>{const f=fixture();db.prepare('UPDATE universities SET active=0 WHERE id=?').run(f.uni);expect((await call('put',`/universities/${f.uni}`,f.admin,{max_students:50})).status).toBe(200);expect(rows('SELECT active FROM universities WHERE id=?',f.uni)[0].active).toBe(0);});
it('university accepts boolean false when deactivating',async()=>{const f=fixture();expect((await call('put',`/universities/${f.uni}`,f.admin,{active:false})).status).toBe(200);expect(rows('SELECT active FROM universities WHERE id=?',f.uni)[0].active).toBe(0);});
for(const selector of ['class_id','class_code','row_code'])it(`CSV rejects foreign ${selector} before creating or enrolling students`,async()=>{const f=fixture(),foreign=actor('student',f.other);db.prepare('UPDATE classes SET university_id=? WHERE id=?').run(f.other,f.cid);const body=selector==='row_code'?{csv:`name,student_no,class_code\nTest,${foreign.username},${f.code}\nTest,new-${f.cid},${f.code}`}:{csv:`name,student_no\nTest,${foreign.username}\nTest,new-${f.cid}`,[selector]:selector==='class_id'?f.cid:f.code};const r=await call('post','/users/import',f.teacher,body);expect([200,403]).toContain(r.status);expect(rows('SELECT * FROM class_members WHERE class_id=?',f.cid)).toHaveLength(0);expect(rows('SELECT * FROM users WHERE username=?',`new-${f.cid}`)).toHaveLength(0);});
for(const [name,spec] of quotas.slice(0,6))it(`${name} does not swallow university-healing SQL errors`,async()=>{const f=fixture();persistNow();db.exec(`CREATE TRIGGER r23_heal BEFORE UPDATE OF university_id ON users WHEN OLD.id=${f.unassigned.id} BEGIN SELECT RAISE(ABORT,'R23 heal failure'); END`);try{expect((await call(...spec(f))).status).toBe(500);expect(rows('SELECT university_id FROM users WHERE id=?',f.unassigned.id)[0].university_id).toBeNull();}finally{db.exec('DROP TRIGGER r23_heal');}});
it('CSV enrolment SQL error rolls back newly created students',async()=>{const f=fixture();persistNow();db.exec(`CREATE TRIGGER r23_enrol BEFORE INSERT ON class_members WHEN NEW.class_id=${f.cid} BEGIN SELECT RAISE(ABORT,'R23 enrol failure'); END`);try{expect((await call('post','/users/import',f.teacher,{csv:`name,student_no\nTest,new-${f.cid}`,class_id:f.cid})).status).toBe(500);expect(rows('SELECT * FROM users WHERE username=?',`new-${f.cid}`)).toHaveLength(0);}finally{db.exec('DROP TRIGGER r23_enrol');}});
for(const [name,spec] of quotas)it(`${name} accepts one newcomer when one seat remains and persists it`,async()=>{const f=fixture();limit(f,1);expect((await call(...spec(f))).status).toBe(200);expect(count(f)).toBe(2);await reloadDb();expect(count(f)).toBe(2);});
for(const [name,spec] of quotas.slice(0,6))it(`${name} allows existing same-university students at capacity`,async()=>{const f=fixture();db.prepare('UPDATE users SET university_id=? WHERE id=?').run(f.uni,f.unassigned.id);limit(f);expect((await call(...spec(f))).status).toBe(200);expect(count(f)).toBe(2);});
it('concurrent creation rechecks the last remaining seat after password hashing',async()=>{const f=fixture();limit(f,1);const results=await Promise.all([call('post','/users',f.teacher,{studentNo:`race-a-${f.cid}`}),call('post','/users',f.teacher,{studentNo:`race-b-${f.cid}`})]);expect(results.map(r=>r.status).sort()).toEqual([200,403]);expect(count(f)).toBe(2);});
it('CSV admin may import into another university via a row class code',async()=>{const f=fixture();const r=await call('post','/users/import',f.admin,{csv:`name,student_no,class_code\nTest,new-${f.cid},${f.code}`});expect(r.status).toBe(200);expect(r.body).toMatchObject({created:1,skipped:0,enrolled:1});expect(count(f)).toBe(2);await reloadDb();expect(rows('SELECT * FROM class_members WHERE class_id=?',f.cid)).toHaveLength(1);});
it('CSV mixed batch counts rejected rows once and never crosses capacity',async()=>{const f=fixture();limit(f,1);const r=await call('post','/users/import',f.teacher,{csv:`name,student_no\nOne,new-a-${f.cid}\nTwo,new-b-${f.cid}\nAgain,new-a-${f.cid}`,class_id:f.cid});expect(r.body).toMatchObject({created:1,skipped:2,total:3,enrolled:1});expect(count(f)).toBe(2);});
it('admin legacy unassigned CSV import remains supported',async()=>{const f=fixture();const r=await call('post','/users/import',f.admin,{csv:`name,student_no\nLegacy,new-${f.cid}`});expect(r.body.created).toBe(1);expect(rows('SELECT university_id FROM users WHERE username=?',`new-${f.cid}`)[0].university_id).toBeNull();});
