import {beforeAll,it,expect} from 'vitest';
import {execFileSync} from 'node:child_process';
import request from 'supertest';
import fs from 'node:fs';
import path from 'node:path';
import {ACADEMIC_DIR} from '../src/lib/paths.js';
import {db,initDb,initSchema,persistNow,reloadDb} from '../src/db.js';
import {createApp} from '../src/app.js';
import {signToken} from '../src/lib/auth.js';
import {ensureArakHistology} from '../src/lib/arak-seed.js';
let app,admin;
beforeAll(async()=>{execFileSync(process.execPath,['src/seed.js','--force'],{stdio:'ignore'});await initDb();app=createApp();admin=signToken(db.prepare("SELECT * FROM users WHERE role='admin' LIMIT 1").get())},60000);
it('fresh seed creates no erroneous university and belongs to real Arak',()=>{
 expect(db.prepare("SELECT id FROM universities WHERE code='ARAK_HIST'").get()).toBeUndefined();
 const real=db.prepare("SELECT id FROM universities WHERE code='ARAK'").get().id;
 expect(db.prepare("SELECT university_id FROM users WHERE username='arak_histology'").get().university_id).toBe(real);
 const before=db.prepare('SELECT COUNT(*) n FROM flashcards').get().n;ensureArakHistology();expect(db.prepare('SELECT COUNT(*) n FROM flashcards').get().n).toBe(before);
});
it('upgrade removes old institution from directory but preserves users/content and private namespace',async()=>{
 const legacyId=Number(db.prepare("INSERT INTO universities(code,name_fa) VALUES ('ARAK_HIST','دانشگاه علوم پزشکی اراک - بافت‌شناسی')").run().lastInsertRowid);
 db.prepare("UPDATE users SET university_id=? WHERE username='arak_histology'").run(legacyId);
 db.prepare('UPDATE flashcards SET university_id=?,active=0 WHERE id=172').run(legacyId);
 const old=db.prepare('SELECT * FROM flashcards WHERE id=172').get();const user=db.prepare("SELECT * FROM users WHERE username='arak_histology'").get();
 const learner=db.prepare("SELECT id FROM users WHERE username='arak_student'").get();
 db.prepare('UPDATE users SET university_id=? WHERE id=?').run(legacyId,learner.id);
 const classId=Number(db.prepare("INSERT INTO classes(name_en,university_id) VALUES ('Legacy history',?)").run(legacyId).lastInsertRowid);
 db.prepare('INSERT INTO class_members(class_id,user_id) VALUES (?,?)').run(classId,learner.id);
 db.prepare('INSERT INTO class_flashcards(class_id,flashcard_id) VALUES (?,172)').run(classId);
 const attemptId=Number(db.prepare("INSERT INTO class_flashcard_attempts(class_id,flashcard_id,user_id,score,answers_json) VALUES (?,172,?,77,'[{\"answer\":\"historical\"}]')").run(classId,learner.id).lastInsertRowid);
 const attempt=db.prepare('SELECT * FROM class_flashcard_attempts WHERE id=?').get(attemptId);
 const media=path.join(ACADEMIC_DIR,`university-${legacyId}`,'media');fs.mkdirSync(media,{recursive:true});fs.writeFileSync(path.join(media,'r35-private.svg'),'<svg xmlns="http://www.w3.org/2000/svg"></svg>');
 persistNow();
 await reloadDb();initSchema();ensureArakHistology();
 expect(db.prepare('SELECT retired_at FROM universities WHERE id=?').get(legacyId).retired_at).toBeTruthy();
 expect(db.prepare('SELECT * FROM flashcards WHERE id=172').get()).toEqual(old);
 expect(db.prepare("SELECT * FROM users WHERE username='arak_histology'").get()).toEqual(user);
 expect(db.prepare('SELECT * FROM class_flashcard_attempts WHERE id=?').get(attemptId)).toEqual(attempt);
 const mediaPath=`/uploads/academic/university-${legacyId}/r35-private.svg`;
 expect((await request(app).get(mediaPath).auth(signToken(user),{type:'bearer'})).status).toBe(200);
 const foreign=db.prepare("SELECT * FROM users WHERE username='arak_teacher'").get();
 expect((await request(app).get(mediaPath).auth(signToken(foreign),{type:'bearer'})).status).toBe(404);
 const list=await request(app).get('/api/universities').auth(admin,{type:'bearer'});expect(list.status).toBe(200);expect(list.body.universities.some(u=>u.code==='ARAK_HIST')).toBe(false);
});
